export const BuildingType = {
  PART_OF: 'PART_OF',
  ROAD: 'ROAD',
  HOUSE: 'HOUSE',
  GENERATOR: 'GENERATOR',
  TREE: 'TREE',
  WALL_BRICKS: 'WALL_BRICKS'
  
}
// ESTO ES DE TEST, AQUI PONER CADA BUILD